// swift-tools-version: 5.9

// WARNING:
// This file is automatically generated.
// Do not edit it by hand because the contents will be replaced.

import PackageDescription
import AppleProductTypes

let package = Package(
    name: "TrueDepthTrigger",
    platforms: [
        .iOS("16.0")
    ],
    products: [
        .iOSApplication(
            name: "TrueDepthTrigger",
            targets: ["AppModule"],
            bundleIdentifier: "com.ksh.TrueDepthTrigger",
            displayVersion: "1.0",
            bundleVersion: "1",
            appIcon: .placeholder(icon: .photo),
            accentColor: .presetColor(.orange),
            supportedDeviceFamilies: [
                .pad,
                .phone
            ],
            supportedInterfaceOrientations: [
                .portrait,
                .landscapeRight,
                .landscapeLeft,
                .portraitUpsideDown(.when(deviceFamilies: [.pad]))
            ],
            capabilities: [
                .camera(purposeString: "TrueDepth 카메라로 거리를 측정합니다."),
                .bluetoothAlways(purposeString: "범위 안일 때 BLE 기기에 True를 전송합니다.")
            ]
        )
    ],
    targets: [
        .executableTarget(
            name: "AppModule",
            path: ".",
            swiftSettings: [
                .enableUpcomingFeature("BareSlashRegexLiterals")
            ]
        )
    ]
)
